# Generated by Django 4.0.4 on 2023-02-18 12:53

import clients.models.client
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientSystem',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID клиента')),
                ('login', models.CharField(max_length=35, unique=True, verbose_name='Логин')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('group', models.CharField(blank=True, max_length=100, null=True, verbose_name='Группа')),
                ('active', models.BooleanField(default=True, verbose_name='Активный')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('secret', models.CharField(blank=True, default=clients.models.client.get_secret, max_length=32, unique=True, verbose_name='Секретный токен')),
                ('is_student', models.BooleanField(default=True, verbose_name='Студент')),
                ('is_teacher', models.BooleanField(default=False, verbose_name='Преподаватель')),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('last_use', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='ClientSystemToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=clients.models.client.get_token, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='clients.clientsystem')),
            ],
        ),
    ]
