# Generated by Django 4.0.4 on 2023-02-18 13:02

import clients.models.client
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsystem',
            name='secret',
        ),
        migrations.AddField(
            model_name='clientsystem',
            name='password',
            field=models.CharField(blank=True, default=clients.models.client.get_secret, max_length=16, unique=True, verbose_name='Секретный токен'),
        ),
    ]
