# Generated by Django 4.0.4 on 2023-02-18 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Лабораторная работа',
                'verbose_name_plural': 'Лабораторные работы',
            },
        ),
        migrations.AlterField(
            model_name='reagents',
            name='place',
            field=models.CharField(default='', max_length=500, verbose_name='Место хранения'),
        ),
        migrations.AlterField(
            model_name='reagents',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.CreateModel(
            name='WorkReagents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(default=0, verbose_name='Количество')),
                ('units', models.IntegerField(choices=[(1, 'mg'), (2, 'g'), (3, 'kg'), (4, 'ml'), (5, 'l')], verbose_name='Единицы измерения')),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_reagents', to='inventory.reagents')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='inventory.work')),
            ],
            options={
                'verbose_name': 'Реагенты для лабораторной работы',
                'verbose_name_plural': 'Реагенты для лабораторной работы',
            },
        ),
    ]
