# Generated by Django 4.0.4 on 2023-02-18 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_remove_clientsystem_secret_clientsystem_password'),
        ('inventory', '0002_work_alter_reagents_place_alter_reagents_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_works', to='clients.clientsystem', verbose_name='Студент')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='inventory.work', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Лабораторная работа студента',
                'verbose_name_plural': 'Лабораторные работы студента',
            },
        ),
        migrations.CreateModel(
            name='StudentWorkReagents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken', models.BooleanField(default=False)),
                ('reagent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.workreagents', verbose_name='Реагент')),
                ('student_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reagents', to='student.studentwork', verbose_name='Работа')),
            ],
            options={
                'verbose_name': 'Лабораторная работа студента',
                'verbose_name_plural': 'Лабораторные работы студента',
            },
        ),
    ]
